In [28]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
reshaped=arr.reshape(3,4)
reshaped

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 120]])

In [7]:
flattend=reshaped.flatten()
flattend

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 120])

In [11]:
flattend=reshaped.flatten()
flattend[0]=99
flattend

array([ 99,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 120])

In [13]:
reshaped

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 120]])

In [22]:
raveled=reshaped.ravel()
raveled[1]=88
raveled

array([  1,  88,   3,   4,   5,   6,   7,   8,   9,  10,  11, 120])

In [24]:
reshaped

array([[  1,  88,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 120]])

In [35]:
arr1=np.array([1,2,3])
arr1
arr2=np.array([2,3,4])
arr2

array([2, 3, 4])

In [51]:
arr-8
arr+9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [43]:
arr1=np.array([1,2,3])
arr1
arr2=np.array([[2],[4],[6]])
arr2

array([[2],
       [4],
       [6]])

In [53]:
arr1+arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [59]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])